-- MatchWiz initial schema

CREATE TABLE app_user (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(100) NOT NULL UNIQUE,
    password_hash       VARCHAR(255) NOT NULL,
    email               VARCHAR(255),
    email_verified      BOOLEAN      NOT NULL DEFAULT FALSE,
    preferred_language  VARCHAR(10),
    timezone            VARCHAR(64),
    theme               VARCHAR(10)  NOT NULL DEFAULT 'SYSTEM',
    two_factor_enabled  BOOLEAN      NOT NULL DEFAULT FALSE,
    email_notifications BOOLEAN      NOT NULL DEFAULT FALSE,
    matchday_reminders  BOOLEAN      NOT NULL DEFAULT FALSE,
    global_role         VARCHAR(20)  NOT NULL DEFAULT 'USER',
    active              BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE competition (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    season      VARCHAR(50)  NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    start_date  DATE,
    end_date    DATE
);

CREATE TABLE scoring_rule (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id          BIGINT  NOT NULL UNIQUE REFERENCES competition(id) ON DELETE CASCADE,
    exact_result_points     INTEGER NOT NULL DEFAULT 5,
    goal_difference_points  INTEGER NOT NULL DEFAULT 3,
    tendency_points         INTEGER NOT NULL DEFAULT 2
);

CREATE TABLE app_group (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id  BIGINT       NOT NULL REFERENCES competition(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    description     TEXT
);
CREATE INDEX idx_group_competition ON app_group(competition_id);

CREATE TABLE group_membership (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT      NOT NULL REFERENCES app_group(id) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    role        VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    approved    BOOLEAN     NOT NULL DEFAULT FALSE,
    joined_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_membership UNIQUE (group_id, user_id)
);
CREATE INDEX idx_membership_user ON group_membership(user_id);

CREATE TABLE invitation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT       NOT NULL REFERENCES app_group(id) ON DELETE CASCADE,
    email       VARCHAR(255) NOT NULL,
    token       VARCHAR(255) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    accepted_at TIMESTAMPTZ
);

CREATE TABLE team (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    short_name  VARCHAR(50)  NOT NULL,
    logo_url    VARCHAR(1024)
);

CREATE TABLE matchday (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id  BIGINT      NOT NULL REFERENCES competition(id) ON DELETE CASCADE,
    number          INTEGER     NOT NULL,
    deadline        TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_matchday_number UNIQUE (competition_id, number)
);

CREATE TABLE match (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matchday_id   BIGINT      NOT NULL REFERENCES matchday(id) ON DELETE CASCADE,
    home_team_id  BIGINT      NOT NULL REFERENCES team(id),
    away_team_id  BIGINT      NOT NULL REFERENCES team(id),
    kickoff_time  TIMESTAMPTZ NOT NULL,
    home_goals    INTEGER,
    away_goals    INTEGER,
    status        VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED'
);
CREATE INDEX idx_match_matchday ON match(matchday_id);

CREATE TABLE prediction (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT      NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    match_id              BIGINT      NOT NULL REFERENCES match(id) ON DELETE CASCADE,
    predicted_home_goals  INTEGER     NOT NULL,
    predicted_away_goals  INTEGER     NOT NULL,
    awarded_points        INTEGER,
    submitted_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_prediction UNIQUE (user_id, match_id)
);
CREATE INDEX idx_prediction_match ON prediction(match_id);
CREATE INDEX idx_prediction_user ON prediction(user_id);

CREATE TABLE notification (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    type        VARCHAR(40)  NOT NULL,
    title       VARCHAR(255) NOT NULL,
    message     TEXT         NOT NULL,
    read        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_notification_user ON notification(user_id);
