CREATE TABLE manual_bonus (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT       NOT NULL REFERENCES app_group(id) ON DELETE CASCADE,
    user_id     BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    awarded_by  BIGINT       NOT NULL REFERENCES app_user(id),
    points      INTEGER      NOT NULL,
    reason      VARCHAR(255),
    awarded_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_manual_bonus_group ON manual_bonus(group_id);
