CREATE TABLE legal_notice (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL DEFAULT '',
    address   TEXT         NOT NULL DEFAULT '',
    telephone VARCHAR(50)  NOT NULL DEFAULT '',
    email     VARCHAR(255) NOT NULL DEFAULT '',
    CONSTRAINT chk_legal_notice_singleton CHECK (id = 1)
);

INSERT INTO legal_notice (name, address, telephone, email) VALUES ('', '', '', '');
